import realHouse1 from '../../assets/images/real house 1.png'
import exquisiteHouse1 from '../../assets/images/exquisite house 1.png'
import luxeHouse1 from '../../assets/images/luxe house 1.png'
import harmonyHouse1 from '../../assets/images/harmony house 1.png'
import realHouse2 from '../../assets/images/real house 2.png'
import realHouse3 from '../../assets/images/real house 3.png'
import infiniteVilla from '../../assets/images/infinte house 1.png'
import realHouse4 from '../../assets/images/real house 4.png'
import realHouse5 from '../../assets/images/real house 5.png'
import link from '../../assets/icons/Link.png'
import video from '../../assets/icons/video.png'
import picture from '../../assets/icons/picture.png'

export const data = [
    {
        id: 1,
        img: realHouse1,
        name: 'Real House Luxury Villa',
        location: 'Victoria Island',
        bedrooms: "6 Bedrooms",
        bathrooms: "3 Bathrooms",
        price: "₦3,340,000,000",
        featured: "Featured",
        saleRent: "For Sale",
        link: link,
        video: video,
        picture: picture,
    },
    {
        id: 2,
        img: exquisiteHouse1,
        name: 'Exquisite Haven Villa',
        location: 'Festac, Lagos',
        bedrooms: "5 Bedrooms",
        bathrooms: "3 Bathrooms",
        price: "₦4,000,000",
        featured: "Featured",
        saleRent: "For Rent",
        link: link,
        video: video,
        picture: picture,
    },
    {
        id: 3,
        img: luxeHouse1,
        name: 'Luxe Palatial Villa',
        location: 'Gbagada, Lagos',
        bedrooms: "7 Bedrooms",
        bathrooms: "3 Bathrooms",
        price: "₦5,340,000,000",
        featured: "Featured",
        saleRent: "For Sale",
        link: link,
        video: video,
        picture: picture,
    },
    {
        id: 4,
        img: harmonyHouse1,
        name: 'Harmony Luxury Villa',
        location: 'Mushin, Lagos',
        bedrooms: "4 Bedrooms",
        bathrooms: "3 Bathrooms",
        price: "₦4,000,000/1 Year",
        featured: "Featured",
        saleRent: "For Rent",
        link: link,
        video: video,
        picture: picture,
    },
    {
        id: 5,
        img: realHouse2,
        name: 'Real House Luxury Villa',
        location: 'Victoria Island',
        bedrooms: "6 Bedrooms",
        bathrooms: "3 Bathrooms",
        price: "₦350,000,000",
        featured: "Featured",
        saleRent: "For Rent",
        link: link,
        video: video,
        picture: picture,
    },
    {
        id: 6,
        img: realHouse3,
        name: 'Real House Luxury Villa',
        location: 'Lekki-Ajah, Lagos',
        bedrooms: "5 Bedrooms",
        bathrooms: "3 Bathrooms",
        price: "₦4,200,000/1 Year",
        featured: "Featured",
        saleRent: "For Sale",
        link: link,
        video: video,
        picture: picture,
    },
    {
        id: 7,
        img: infiniteVilla,
        name: 'Infinite Bliss Villa',
        location: 'Ishiagu, Enugu',
        bedrooms: "5 Bedrooms",
        bathrooms: "3 Bathrooms",
        price: "₦2,350,000,000",
        featured: "Featured",
        saleRent: "For Sale",
        link: link,
        video: video,
        picture: picture,
    },
    {
        id: 8,
        img: realHouse4,
        name: 'Real House Luxury Villa',
        location: 'Works Layout, Owerri',
        bedrooms: "8 Bedrooms",
        bathrooms: "6 Bathrooms",
        price: "₦3,350,000/1 Year",
        featured: "Featured",
        saleRent: "For Rent",
        link: link,
        video: video,
        picture: picture,
    },
    {
        id: 9,
        img: realHouse5,
        name: 'Real House Luxury Villa',
        location: 'Ikeja, Lagos',
        bedrooms: "6 Bedrooms",
        bathrooms: "6 Bathrooms",
        price: "₦600,000,000",
        featured: "Featured",
        saleRent: "For Sale",
        link: link,
        video: video,
        picture: picture,
    },
]